name: PublishDocumentation

on: 
  push:
    branches: [master]
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy_docs:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Build DocC Documentation
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target HumanString \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path HumanString \
          --output-path docs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true